environment:
  matrix:
    # - nodejs_version: 7
    - nodejs_version: 6
    - nodejs_version: 4

matrix:
  fast_finish: true

cache:
  - 'node_modules'

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - npm install -g npm@latest --loglevel=warn
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --loglevel=warn

test_script:
  - node --version
  - npm --version
  - npm run test

cache:
  - 'node_modules'
